// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6R1ZAvIAzvfkWBRhd6r54o6V_UdZwvbg',
    appId: '1:591676938616:web:f663afe0492e0a291bd08d',
    messagingSenderId: '591676938616',
    projectId: 'pilot-toolbox-98b8e',
    authDomain: 'pilot-toolbox-98b8e.firebaseapp.com',
    storageBucket: 'pilot-toolbox-98b8e.firebasestorage.app',
    measurementId: 'G-YLWD4N20QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjiNczEMzvTw4LKEJLXWPQRvR98Twh6w',
    appId: '1:591676938616:android:af68f5acf5a7f3cf1bd08d',
    messagingSenderId: '591676938616',
    projectId: 'pilot-toolbox-98b8e',
    storageBucket: 'pilot-toolbox-98b8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV43OUIz8LyWn_8FwtwXztz4Oc4x_1TQc',
    appId: '1:591676938616:ios:b6730200f2e82f0c1bd08d',
    messagingSenderId: '591676938616',
    projectId: 'pilot-toolbox-98b8e',
    storageBucket: 'pilot-toolbox-98b8e.firebasestorage.app',
    iosBundleId: 'com.example.pilotToolbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV43OUIz8LyWn_8FwtwXztz4Oc4x_1TQc',
    appId: '1:591676938616:ios:b6730200f2e82f0c1bd08d',
    messagingSenderId: '591676938616',
    projectId: 'pilot-toolbox-98b8e',
    storageBucket: 'pilot-toolbox-98b8e.firebasestorage.app',
    iosBundleId: 'com.example.pilotToolbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6R1ZAvIAzvfkWBRhd6r54o6V_UdZwvbg',
    appId: '1:591676938616:web:77fde417b285ea2f1bd08d',
    messagingSenderId: '591676938616',
    projectId: 'pilot-toolbox-98b8e',
    authDomain: 'pilot-toolbox-98b8e.firebaseapp.com',
    storageBucket: 'pilot-toolbox-98b8e.firebasestorage.app',
    measurementId: 'G-LW1P9PWXH2',
  );

}